### ISSUE TITLE
npm run dev build error

### ISSUE THREAD

**Issue by bendkaye613** [jacob-ebey/remix-dashboard-template#8]
> dev
> npm run build && concurrently "npm:dev:*"

> build
> npm run build:css && remix build

> build:css
> postcss ./styles/global.css -d ./app/styles

Building Remix app in production mode...
Error: Unable to define routes with duplicate route id: "routes/_dashboard.items"
    at defineRoute (/Users/bendkaye/remix/example-dashboard/node_modules/@remix-run/dev/dist/config/routes.js:73:13)
    at routeChildren (/Users/bendkaye/remix/example-dashboard/node_modules/remix-flat-routes/dist/index.js:137:17)
    at defineRoute (/Users/bendkaye/remix/example-dashboard/node_modules/@remix-run/dev/dist/config/routes.js:78:7)
    at getRoutes (/Users/bendkaye/remix/example-dashboard/node_modules/remix-flat-routes/dist/index.js:140:9)
    at routeChildren (/Users/bendkaye/remix/example-dashboard/node_modules/remix-flat-routes/dist/index.js:133:17)
    at defineRoute (/Users/bendkaye/remix/example-dashboard/node_modules/@remix-run/dev/dist/config/routes.js:78:7)
    at getRoutes (/Users/bendkaye/remix/example-dashboard/node_modules/remix-flat-routes/dist/index.js:140:9)
    at /Users/bendkaye/remix/example-dashboard/node_modules/remix-flat-routes/dist/index.js:77:9
    at defineRoutes (/Users/bendkaye/remix/example-dashboard/node_modules/@remix-run/dev/dist/config/routes.js:82:3)
    at flatRoutes (/Users/bendkaye/remix/example-dashboard/node_modules/remix-flat-routes/dist/index.js:47:18)

**Comment by no2chem** [comment]
This issue appears to be fixable by updating remix-flat-routes:

`npm i -D remix-flat-routes@0.5.8`
